services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    group_add:
      - 998
    volumes:
      - /data/jellyfin/config:/config
      - /data/jellyfin/cache:/cache
      - type: bind
        source: /home/media
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

networks:
  default:
    external: true
    name: npm
