services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  default:
    name: npm
